# Generated by Django 3.0.3 on 2020-03-20 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('product_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=500)),
                ('prize', models.IntegerField()),
                ('image', models.ImageField(upload_to='')),
            ],
        ),
    ]
