# Generated by Django 3.0.3 on 2020-03-20 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20200320_0330'),
    ]

    operations = [
        migrations.CreateModel(
            name='banner',
            fields=[
                ('banner_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('url', models.CharField(max_length=200)),
                ('text', models.CharField(max_length=500)),
                ('status', models.BooleanField()),
            ],
        ),
    ]
