# Generated by Django 3.0.3 on 2020-03-20 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_auto_20200320_0336'),
    ]

    operations = [
        migrations.CreateModel(
            name='contact_us',
            fields=[
                ('msg_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=200)),
                ('msg', models.CharField(max_length=500)),
            ],
        ),
    ]
