# Generated by Django 3.0.3 on 2020-03-20 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_contact_us'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_us',
            name='status',
            field=models.BooleanField(default=0),
        ),
    ]
