# Generated by Django 3.0.3 on 2020-04-08 14:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_orderupdate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='order_update',
        ),
        migrations.DeleteModel(
            name='orderUpdate',
        ),
    ]
