# Generated by Django 3.0.3 on 2020-04-08 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0013_order_update'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order_update',
            name='email',
            field=models.EmailField(default='No action perform', max_length=254),
        ),
    ]
